#' @title \emph{meshTest}: Visualize an INLA Mesh
#'
#' @description Visualize an INLA mesh to check its parameters before using it in a model run.
#'
#' @param meshList A list containing mesh parameters such as cutoff, max.edge, and offset.
#' @param regionGeometry An 'sf' object representing the study region. Generated by 'defineRegion'.
#' @param print Logical, if TRUE, the mesh will be plotted automatically.
#' @param crs Coordinate Reference System (CRS). If NULL, the CRS of regionGeometry is used.
#' 
#' @return A 'ggplot' object depicting the INLA mesh.
#'
#' @importFrom sf st_transform st_crs
#' @importFrom ggplot2 ggplot geom_sf
#' @importFrom INLA inla.mesh.2d
#' @importFrom inlabru fm_as_inla_mesh_segment fm_crs gg

meshTest <- function(meshList, regionGeometry, print = TRUE, crs = NULL) {
  # Load required packages
  require(sf)
  require(ggplot2)
  require(INLA)
  require(inlabru)
  
  # Define CRS if not provided
  if(is.null(crs)) {
    crs <- st_crs(regionGeometry)$wkt
  } else {
    crs <- st_crs(crs)$wkt  # Standardize CRS into well-known text format
  }
  
  # Create mesh using INLA and inlabru
  mesh <- inla.mesh.2d(boundary = fm_as_inla_mesh_segment(st_transform(regionGeometry, crs)),
                             crs = fm_crs(crs),
                             cutoff = meshList$cutoff, 
                             max.edge = meshList$max.edge, 
                             offset = meshList$offset)
  
  # Plotting mesh
  meshPlot <- ggplot() +
    geom_sf(data = st_transform(regionGeometry, crs), fill = "white") +
    gg(mesh)
  
  if (print) { print(meshPlot) }
  
  return(mesh)
}
