#' @title \emph{meshTest}: Visualize an INLA Mesh
#'
#' @description Visualize an INLA mesh to check its parameters before using it in a model run.
#'
#' @param meshList A list containing mesh parameters such as cutoff, max.edge, and offset.
#' @param regionGeometry An 'sf' object representing the study region. Generated by 'defineRegion'.
#' @param print Logical, if TRUE, the mesh will be plotted automatically.
#' @param crs Coordinate Reference System (CRS). If NULL, the CRS of regionGeometry is used.
#' 
#' @return A 'ggplot' object depicting the INLA mesh.
#'
#' @importFrom sf st_transform st_crs
#' @importFrom ggplot2 ggplot geom_sf
#' @importFrom INLA inla.mesh.2d
#' @importFrom inlabru fm_as_inla_mesh_segment fm_crs gg

meshTest <- function(meshList, regionGeometry, print = TRUE, crs = NULL) {
  # Load required packages
  require(sf)
  require(ggplot2)
  require(INLA)
  require(inlabru)
  
  # Define CRS if not provided
  if(is.null(crs)) {
    crs <- st_crs(regionGeometry)$wkt
  } else {
    crs <- st_crs(crs)$wkt  # Standardize CRS into well-known text format
  }
  
  # make a two extension hulls and mesh for spatial model
  hull <- fm_extensions(
    regionGeometry,
    convex = meshList$max.edge*2,
    concave = meshList$max.edge*2
  )
  
  # Create mesh using INLA and inlabru
  mesh <-  fm_mesh_2d_inla(
    boundary = hull, 
    max.edge = meshList$max.edge, # km inside and outside
    cutoff = meshList$cutoff,  # cutoff is min edge
    offset = meshList$offset,
    crs = fm_crs(crs)
  )
  
  # Plotting mesh
  meshPlot <- ggplot() +
    geom_sf(data = st_transform(regionGeometry, crs), fill = "white") +
    gg(mesh)
  
  if (print) { print(meshPlot) }
  
  return(mesh)
}