[project]
name = "biodiv-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.93",
    "dask>=2026.7.1",
    "geopandas>=1.1.4",
    "ipython>=9.15.0",
    "netcdf4>=1.7.4",
    "pyproj>=3.7.2",
    "rasterio>=1.5.0",
    "requests>=2.34.2",
    "rioxarray>=0.23.0",
    "shapely>=2.1.2",
]
