---
title: Visualisation Of The Open Data Biodiversity Mapper - Software Documentation
output:
  html_document:
    toc: true
    toc_depth: 2
---

```{css style settings, echo = FALSE, include = FALSE}
blockquote {
    padding: 10px 20px;
    margin: 0 0 20px;
    font-size: 10px;
    border-left: 5px solid #eee;
}
```

# Introduction

The Open Data Biodiversity Mapper (ODBM) is a tool intended to provide information on biodiversity hotspots within Norway. It highlights
regions where red-listed species are likely to be found, for the purposes of enabling policy decisions regarding the
protection or restoration of said regions. The tool uses openly available data, fed through integrated species distribution
models, to analyse where these regions can be found in Norway.

The following document provides all the information needed to understand the communication tool chosen to visualise results - a Shiny app. It will detail
the set-up of the tool, as well as the code required to produce it. For any further information, or to make requests for additions to the documentation, 
please contact Sam Wenaas Perrin at sam.perrin@ntnu.no.

# Data Provision

All code used to turn the raw data into the Shiny app can be found in the **[BioDivMapping Github repository](https://github.com/gjearevoll/BioDivMapping)**
in the folder `visualisation`. All code used to produce said data can be found throughout the rest of the repository - this is detailed in a separate 
document, entitled "The Open Data Biodiversity Mapper - Software Documentation".

The Shiny app is split into two files - server.R and ui.R. For more information on how a Shiny app functions with regard to user interface and server
interaction, you can check out Shiny's [Welcome to Shiny walkthrough](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/index.html).

An alpha version of the Shiny app is available [at this link](https://swp-data-projects.shinyapps.io/odbm/).

As opposed to the documentation for the rest of the data pipeline, here the tool description will be structured after the tabs that make up the Shiny tool.

## Species Intensities

This tab visualises the predicted species intensities. Data here is a product of species intensity modelling as detailed in section 3.2. Species intensity 
is scaled to between 0 and 1. It is important to note at this point that a single species' intensity in our mapping tool is currently only relative to that 
species. That is to say that a species intensity of 0.5 on a fairly common species and of 0.5 on a very rare species do not imply the same likelihood of 
occurrence.

The option is also provided to show observed species occurrences as derived from processing GBIF data. Additionally, an image of the species downloaded 
directly from iNaturalist, as well as the total number of observations and red list status is provided in a supplementary window.

## Predicted species richness

This tab visualises predicted species richness as derived from iSDMs. The option is also given to display species richness for all species within a given 
taxa, or only red-listed species within the same taxa.

## Observed species richness

This tab visualises observed species richness as a product of overlaying unique observations of species within a given pixel. Observed species richness is 
displayed separately from predicted species richness. Species richness here is aggregated to provide better visibility, as some species have relatively 
small, concentrated observation clusters.

## Environmental covariates

This tab displays aggregated rasters representing the environmental covariates used in the model. Note that these variables are currently scaled - 
future version will include raw number scales to provide more clarity on value ranges.

## Metadata

This tab includes a report which gives enough data to allow reproducibility of the pipeline. It contains species run, the date of the pipeline run, datasets 
used, environmental covariates used, and information regarding the region. It also includes distribution of red listed species among species groups, and 
distribution of observations among datasets and datatypes.

As a final note, in the near future model uncertainty for both predicted individual species intensities and predicted species richness will be available in
the relevant tabs.




